// ============================================================
//  render.js — Reads data.js and builds the entire page.
//  DO NOT EDIT THIS FILE to change content — edit data.js instead.
// ============================================================

(function () {
  const d = portfolioData;

  /* ── helpers ─────────────────────────────────────────────── */
  const el  = id => document.getElementById(id);
  const set = (id, html) => { if (el(id)) el(id).innerHTML = html; };

  /* ── SEO / META ─────────────────────────────────────────── */
  if (d.seo) {
    document.title = d.seo.title || document.title;
    const desc = document.querySelector('meta[name="description"]');
    const kw   = document.querySelector('meta[name="keywords"]');
    if (desc) desc.setAttribute("content", d.seo.description || "");
    if (kw)   kw.setAttribute("content",  d.seo.keywords    || "");
  }

  /* ── HEADER ─────────────────────────────────────────────── */
  set("header-name", d.personal.name);

  const hs = d.socialLinks;
  set("header-social-links", `
    <a href="${hs.linkedin}" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>
    <a href="${hs.github}"   target="_blank" class="github"><i class="bx bxl-github"></i></a>
    <a href="mailto:${hs.email}" target="_blank" class="google"><i class="bx bxl-google"></i></a>
    ${hs.leetcode ? `<a href="${hs.leetcode}" target="_blank" class="twitter"><i class="bx bx-code-alt"></i></a>` : ""}
  `);

  /* ── ABOUT ──────────────────────────────────────────────── */
  const aboutPhoto = document.getElementById("about-photo");
  if (aboutPhoto) aboutPhoto.src = d.personal.photo;
  set("about-bio", d.personal.bio);

  const a = d.about;
  // Build left column items dynamically based on what exists in data
  const leftItems = [
    a.phone      ? `<li><i class="icofont-rounded-right"></i> <strong>Phone:</strong> ${a.phone}</li>` : "",
    a.city       ? `<li><i class="icofont-rounded-right"></i> <strong>City:</strong> ${a.city}</li>` : "",
    a.graduation ? `<li><i class="icofont-rounded-right"></i> <strong>Graduation:</strong> ${a.graduation}</li>` : "",
  ].join("");
  const rightItems = [
    a.email   ? `<li><i class="icofont-rounded-right"></i> <strong>Email:</strong> ${a.email}</li>` : "",
    a.email2  ? `<li><i class="icofont-rounded-right"></i> <strong>Alt Email:</strong> ${a.email2}</li>` : "",
    a.degree  ? `<li><i class="icofont-rounded-right"></i> <strong>Degree:</strong> ${a.degree}</li>` : "",
    a.birthday? `<li><i class="icofont-rounded-right"></i> <strong>Birthday:</strong> ${a.birthday}</li>` : "",
  ].join("");
  set("about-col-left",  leftItems);
  set("about-col-right", rightItems);

  /* ── INTERESTS ──────────────────────────────────────────── */
  set("interests-container", d.interests.map((item, i) => `
    <div class="col-lg-3 col-md-4 ${i > 0 ? "mt-4 mt-md-0" : ""}">
      <div class="icon-box">
        <i class="${item.icon}" style="color:${item.color};"></i>
        <h3>${item.title}</h3>
      </div>
    </div>
  `).join(""));

  /* ── EDUCATION ──────────────────────────────────────────── */
  set("education-container", d.education.map(edu => `
    <div class="col-md-4 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100"
      style="padding:0px 0px;padding-bottom:5px;display:inline-block;">
      <img src="${edu.logo}" class="img-fluid" alt="">
      <p style="text-align:left;color:#fff;padding:5px 10px;"><em>${edu.degree}</em></p>
      ${edu.institution ? `<p style="text-align:left;color:#12d640;padding:0 10px;font-weight:600;">${edu.institution}</p>` : ""}
      <h5 style="text-align:left;padding:0px 10px;">${edu.duration}</h5>
      ${edu.coursework && edu.coursework.length ? `
        <ul style="text-align:left;color:#fff;">
          ${edu.coursework.map(c => `<li>${c}</li>`).join("")}
        </ul>` : ""}
    </div>
  `).join(""));

  /* ── CERTIFICATIONS ─────────────────────────────────────── */
  set("certification-container", d.certifications.map(cert => `
    <div class="col-lg-4 col-md-6 portfolio-item filter-app">
      <div class="portfolio-wrap">
        <img src="${cert.image}" class="img-fluid" alt="" style="opacity:0;">
        <div class="portfolio-info" style="opacity:1;bottom:0;">
          <h4>${cert.title}</h4>
          <p>${cert.issuer}</p>
          ${cert.credentialId ? `<p style="font-size:11px;color:#aaa;">${cert.credentialId}</p>` : ""}
          ${cert.duration     ? `<p style="font-size:11px;color:#aaa;">${cert.duration}</p>` : ""}
          <div class="portfolio-links">
            <a href="${cert.link}" target="_blank" title="Certificate"><i class="bx bx-link"></i></a>
          </div>
        </div>
      </div>
    </div>
  `).join(""));

  /* ── EXPERIENCE ─────────────────────────────────────────── */
  const exp = d.experience;
  let expHTML = `
    <div class="col-md-12 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100"
      style="margin-bottom:30px;text-align:center;">
      <h4 style="color:#fff;margin-bottom:0;">${exp.seekingMessage}</h4>
    </div>
  `;
  if (exp.hackathons && exp.hackathons.length) {
    expHTML += `<h3 style="color:#fff;margin-bottom:20px;font-weight:600;">Hackathons</h3>`;
    expHTML += exp.hackathons.map(h => `
      <div class="col-md-12 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100">
        <h4 style="text-align:left;">
          <a href="${h.link}" style="color:#12d640">${h.title}</a><br>
        </h4>
        <h5 style="text-align:left;">${h.date}</h5>
        ${h.subtitle ? `<p style="text-align:left;color:#fff"><em>${h.subtitle}</em></p>` : ""}
        <ul style="text-align:left;">
          ${h.bullets.map(b => `<li style="color:#fff;">${b}</li>`).join("")}
        </ul>
      </div>
    `).join("");
  }
  set("experience-container", expHTML);

  /* ── PROJECT FILTER TABS ─────────────────────────────────── */
  set("portfolio-flters", d.projectFilters.map((f, i) => `
    <li data-filter="${f.filter}" ${i === 0 ? 'class="filter-active"' : ""}>${f.label}</li>
  `).join(""));

  /* ── PROJECTS ────────────────────────────────────────────── */
  set("projects-container", d.projects.map(p => `
    <div class="col-lg-4 col-md-6 portfolio-item ${p.filter}">
      <center>
        <h4>${p.title}</h4>
        ${p.duration ? `<p style="color:#aaa;font-size:13px;margin:-8px 0 4px;">${p.duration}</p>` : ""}
      </center>
      <div class="portfolio-wrap">
        <img src="${p.image}" class="img-fluid" alt="">
        <div class="portfolio-info">
          ${p.tech ? `<p style="font-size:12px;color:#12d640;padding:4px 8px;">${p.tech}</p>` : ""}
          <div class="portfolio-links">
            ${p.link && p.link !== "#"
              ? `<a href="${p.link}" target="_blank" title="Live Demo"><i class="bx bx-link-external"></i></a>`
              : ""}
            ${p.detailPage
              ? `<a href="${p.detailPage}" data-gall="portfolioDetailsGallery" data-vbtype="iframe"
                   class="venobox" title="Project Details"><i class="bx bx-info-circle"></i></a>`
              : ""}
          </div>
        </div>
      </div>
    </div>
  `).join(""));

  /* ── SKILLS ─────────────────────────────────────────────── */
  set("skills-container", d.skills.map(s => `
    <div class="col-md-12 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100"
      style="background:rgba(255,255,255,0.05);padding:20px;border-radius:10px;">
      <h4 style="text-align:left;color:#12d640">${s.category}</h4>
      <p style="text-align:left;color:#fff;font-size:16px;margin-bottom:0;">${s.items}</p>
    </div>
  `).join(""));

  /* ── RESUME & LINKS ──────────────────────────────────────── */
  set("links-container", d.links.map(l => `
    <div class="col-md-3 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100">
      <a href="${l.url}" target="_blank">
        <div class="icon"><i class="${l.icon}"></i></div>
      </a>
      <h4 class="title"><a href="${l.url}" target="_blank">${l.title}</a></h4>
      <p class="description" style="color:#fff;">${l.description}</p>
    </div>
  `).join(""));

  /* ── CONTACT ─────────────────────────────────────────────── */
  const c  = d.contact;
  const cl = d.contact.socialLinks || d.socialLinks;
  set("contact-container", `
    <div class="col-md-6 d-flex align-items-stretch">
      <div class="info-box">
        <i class="bx bx-map"></i>
        <h3>My Address</h3>
        <p>${c.address.line1}</p>
        <p>${c.address.line2}</p>
        <p>${c.address.line3}</p>
      </div>
    </div>

    <div class="col-md-6 mt-4 mt-md-0 d-flex align-items-stretch">
      <div class="info-box">
        <i class="bx bx-share-alt"></i>
        <h3>Social Profiles</h3>
        <div class="social-links">
          <a href="${cl.linkedin}" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>
          <a href="${cl.github}"   target="_blank" class="github"><i class="bx bxl-github"></i></a>
          <a href="mailto:${cl.email}" target="_blank" class="google"><i class="bx bxl-google"></i></a>
        </div>
      </div>
    </div>

    <div class="col-md-6 mt-4 d-flex align-items-stretch">
      <div class="info-box">
        <i class="bx bx-envelope"></i>
        <h3>Email</h3>
        ${c.emails.map(e => `<p>${e}</p>`).join("")}
      </div>
    </div>

    ${c.phone ? `
    <div class="col-md-6 mt-4 d-flex align-items-stretch">
      <div class="info-box">
        <i class="bx bx-phone-call"></i>
        <h3>Phone</h3>
        <p>${c.phone}</p>
      </div>
    </div>` : ""}
  `);

  /* ── TYPED.JS ────────────────────────────────────────────── */
  new Typed('.typing', {
    strings: d.personal.typingStrings,
    loop: true,
    typeSpeed: 65,
    backSpeed: 65,
  });

})();
